# Generated by Django 5.1 on 2024-11-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('worker', 'worker'), ('admin', 'admin')], default='worker'),
        ),
    ]
