# Generated by Django 5.1 on 2024-11-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
