# Generated by Django 5.1 on 2024-11-26 15:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(help_text='Stock Keeping Unit identifier', max_length=100, unique=True)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Furniture', 'Furniture'), ('Groceries', 'Groceries'), ('Toys', 'Toys'), ('Books', 'Books'), ('Others', 'Others')], default='Others', help_text='Category of the item', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('minimum_stock_level', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aisle', models.CharField(help_text='Aisle identifier, e.g., A1', max_length=10)),
                ('row', models.CharField(help_text='Row identifier, e.g., R1', max_length=10)),
                ('level', models.CharField(help_text='Level identifier, e.g., L2', max_length=10)),
                ('bin', models.CharField(help_text='Bin identifier, e.g., B3', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('aisle', 'row', 'level', 'bin')},
            },
        ),
        migrations.CreateModel(
            name='ItemLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Quantity of the item at this location')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_locations', to='item.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_locations', to='item.location')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Positive for additions, negative for removals')),
                ('transaction_type', models.CharField(choices=[('add', 'Add Stock'), ('remove', 'Remove Stock'), ('transfer', 'Transfer Stock')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='item.item')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.location')),
            ],
        ),
    ]
