# Generated by Django 5.1 on 2024-11-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Furniture', 'Furniture'), ('Groceries', 'Groceries'), ('Toys', 'Toys'), ('Books', 'Books'), ('Others', 'Others')], default='Others', help_text='Category of the item', max_length=50),
        ),
    ]
