# Generated by Django 5.1 on 2024-11-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='minimum_stock_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
