# Generated by Django 5.1 on 2024-11-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_minimum_stock_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aisle', models.CharField(help_text='Aisle identifier, e.g., A1', max_length=10)),
                ('row', models.CharField(help_text='Row identifier, e.g., R1', max_length=10)),
                ('level', models.CharField(help_text='Level identifier, e.g., L2', max_length=10)),
                ('bin', models.CharField(help_text='Bin identifier, e.g., B3', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Quantity of the item at this location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, help_text='The item stored at this location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='item.item')),
            ],
            options={
                'unique_together': {('aisle', 'row', 'level', 'bin')},
            },
        ),
    ]
