# Generated by Django 5.1 on 2024-11-25 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_stocktransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='item',
        ),
        migrations.RemoveField(
            model_name='location',
            name='quantity',
        ),
        migrations.CreateModel(
            name='ItemLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Quantity of the item at this location')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_locations', to='item.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_locations', to='item.location')),
            ],
            options={
                'unique_together': {('item', 'location')},
            },
        ),
    ]
