# Generated by Django 5.1 on 2024-11-25 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_remove_location_item_remove_location_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
