# Generated by Django 5.1 on 2024-11-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_remove_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
